teams= {
    "gre":"Greece",
    "rus":"Russia",
    "ned":"Netherlands",
    "ger":"Germany",
    "por":"Portugal",
    "esp":"Spain",
    "ita":"Italy",
    "cro":"Croatia",
    "fra":"France",
    "eng":"England",
    "sui":"Switzerland",
    "bel":"Belgium",
    "bih":"Bosnia-Herzegovina",
    "alg":"Algeria",
    "civ":"C\u00f4te d'Ivoire",
    "gha":"Ghana",
    "cmr":"Cameroon",
    "nga":"Nigeria",
    "mex":"Mexico",
    "usa":"United States",
    "hon":"Honduras",
    "crc":"Costa Rica",
    "arg":"Argentina",
    "bra":"Brazil",
    "chi":"Chile",
    "uru":"Uruguay",
    "col":"Colombia",
    "ecu":"Ecuador",
    "aus":"Australia",
    "jpn":"Japan",
    "kor":"South Korea",
    "irn":"Iran"
}
  
