# Generated by Django 2.0.6 on 2018-06-07 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('datetime', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateTimeField(verbose_name='date entered')),
                ('pick_name', models.CharField(max_length=80)),
                ('total_goals', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_truth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_regularized', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=80)),
                ('goals_scored', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('group_advancer_points', models.PositiveIntegerField(default=2)),
                ('group_perfect_points', models.PositiveIntegerField(default=5)),
                ('qf_points', models.PositiveIntegerField(default=4)),
                ('sf_points', models.PositiveIntegerField(default=8)),
                ('f_points', models.PositiveIntegerField(default=16)),
                ('third_place_points', models.PositiveIntegerField(default=16)),
                ('champ_points', models.PositiveIntegerField(default=32)),
                ('team_shutout_points', models.PositiveIntegerField(default=3)),
                ('striker_goals_points', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80)),
                ('country_regularized', models.CharField(max_length=80)),
                ('group_rank', models.IntegerField(default=4)),
                ('furthest_round', models.IntegerField(default=0)),
                ('shutouts', models.IntegerField(default=0)),
                ('is_third_place', models.BooleanField(default=False)),
                ('is_champion', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmgame.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created', models.DateField()),
                ('picks', models.ManyToManyField(related_name='picks', to='vmgame.Pick')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='defensive_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defensive_team', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='final_teams',
            field=models.ManyToManyField(related_name='final_teams', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='group_fourth',
            field=models.ManyToManyField(related_name='group_fourth', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='group_runners_up',
            field=models.ManyToManyField(related_name='group_runners_up', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='group_third',
            field=models.ManyToManyField(related_name='group_third', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='group_winners',
            field=models.ManyToManyField(related_name='group_winners', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='quarterfinal_teams',
            field=models.ManyToManyField(related_name='quarterfinal_teams', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='scoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmgame.Scoring'),
        ),
        migrations.AddField(
            model_name='pick',
            name='semifinal_teams',
            field=models.ManyToManyField(related_name='semifinal_teams', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='strikers',
            field=models.ManyToManyField(related_name='strikers', to='vmgame.Player'),
        ),
        migrations.AddField(
            model_name='pick',
            name='third_place_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place_team', to='vmgame.Team'),
        ),
        migrations.AddField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmgame.UserProfile'),
        ),
    ]
