# Generated by Django 2.0.6 on 2018-06-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion', to='vmgame.Team'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='defensive_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defensive_team', to='vmgame.Team'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='scoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmgame.Scoring'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='third_place_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_team', to='vmgame.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmgame.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmgame.Group'),
        ),
    ]
